### ISSUE TITLE
Hello_World_Deep_Learning source does not match article

### ISSUE THREAD

**Issue by chafey** [ImagingInformatics/machine-learning#4]
The jupyter notebook source code here:

https://github.com/paras42/Hello_World_Deep_Learning/blob/9921a12c905c00a88898121d5dc538e3b524e520/HelloWorldDeepLearning.ipynb

does not match the source described in the article here:

https://link.springer.com/article/10.1007/s10278-018-0079-6

I would expect the article to match the source and there be a link to newer/better source if available - right now it is confusing.

**Comment by sglanger** [comment]
Hi Chris. Steve here. I'm not sure how once an article is published it can ever be synced to an evolving piece of code. I think the best we can hope for is that the authors link to latest version.
